apiVersion: v1
kind: Service
metadata:
  name: danproject
spec:
  selector:
    app: lbg4-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: maria
  labels:
    app: lbg4-api
spec:
  containers:
  - name: maria
    image: gcr.io/lbg-210322/danproject
    ports:
    - containerPort: 80
