apiVersion: v1
kind: Service
metadata:
  name: danproject
spec:
  selector:
    app: lbg4-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: maria
  labels:
    app: lbg4-api
spec:
  containers:
  - name: maria
    image: gcr.io/lbg-210322/danproject
    ports:
    - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: danproject
spec:
  type: LoadBalancer
  selector:
    app: lbg4-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: danproject
  labels:
    app: lbg4-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lbg4-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: lbg4-api
    spec:
      containers:
      - name: danproject
        image: gcr.io/lbg-210322/danproject
        ports:
        - containerPort: 5000
